customhost = "employeerds.csmqnqay16nd.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "aws123456"
customdb = "EmployeeRDS"
custombucket = "gohwanqi-employee-bucket"
customregion = "us-east-1"
